[package]
name = "gt6n_er"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lotus-extra = { git = "https://github.com/Oriolus-Software/lotus-extra.git" }
lotus-script = { git = "https://github.com/Oriolus-Software/LOTUS-Scripting.git", features = [
	"time",
] }
pandemist_vehicle_elements = { git = "https://github.com/Pandemist/PandemistVehicleElements.git" }
time = "0.3"
typedmap = "0.6.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
lto = true
debug = false
panic = "abort"
strip = true
codegen-units = 1

[profile.dev]
opt-level = 1
